### ISSUE TITLE
Rate limit!

### ISSUE THREAD

**Issue by nathan-d** [lil-cain/jim#9]
Our friend in PS is talking about DDoS'ing our project. We need to rate limit his ass.

**Comment by RichieSM** [comment]
I'd suggest writing the current Unix timestamp to a text file every time the status is changed.
Then when a new request comes in, read that file and then: `!if time() > $timetampFromFile { echo "Rate limit exceeded\n"; exit(1); }`.

**Comment by nathan-d** [comment]
Probably better doing something with a tick value limit and use a channel to serve the requests. You can add an in memory buffer with a max number of events to handle bursts of API calls but I doubt our API implementation is going to go that far.
